//! Wire message types for the Continuity protocol.
//!
//! This crate has no I/O of its own — `continuity-net` owns framing,
//! transport, and the mDNS TXT record encoding. Keeping the schema here
//! and dependency-free means it can be reused unchanged by the mobile FFI
//! layer and by `docs/protocol.md` examples.

use serde::{Deserialize, Serialize};

/// Binary payloads (clipboard content, file chunks) are base64-encoded
/// inside the JSON envelope rather than left as a plain `Vec<u8>` — serde's
/// default array-of-numbers encoding for bytes blows up 4-5x, which starts
/// to matter once file chunks are real traffic. Base64 costs ~1.33x instead.
mod b64 {
    use base64::Engine;
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    pub fn serialize<S: Serializer>(bytes: &Vec<u8>, s: S) -> Result<S::Ok, S::Error> {
        base64::engine::general_purpose::STANDARD
            .encode(bytes)
            .serialize(s)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<u8>, D::Error> {
        let s = String::deserialize(d)?;
        base64::engine::general_purpose::STANDARD
            .decode(&s)
            .map_err(serde::de::Error::custom)
    }
}

/// Bump when a breaking change is made to `Message`. Peers exchange this in
/// `DeviceAnnounce` / mDNS TXT records and should refuse to pair on mismatch
/// once the protocol leaves v1 (v1 stays permissive while things are still
/// moving).
pub const PROTOCOL_VERSION: u32 = 1;

/// Hex-encoded Ed25519 public key. This is the device's permanent identity.
pub type DeviceId = String;

/// Hex-encoded content hash (see `continuity-crypto::hash`), used for
/// clipboard-echo suppression and file integrity checks.
pub type ContentHash = String;

/// Opaque id for an in-flight file transfer, generated by the sender.
pub type TransferId = String;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Platform {
    MacOs,
    Windows,
    Linux,
    Android,
    Ios,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DeviceInfo {
    pub id: DeviceId,
    pub name: String,
    pub platform: Platform,
    pub protocol_version: u32,
}

/// A message exchanged on the persistent TLS connection between two paired
/// devices. Framed by `continuity-net` as a u32-BE length prefix followed by
/// a JSON payload (see `continuity_net::framing`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Message {
    /// Sent immediately after a raw TCP connection is established, before
    /// pairing is confirmed — lets each side identify who's on the wire.
    DeviceAnnounce { device: DeviceInfo },

    /// First message of the pairing handshake, sent by the initiating
    /// device. `fingerprint_material` is the initiator's long-term public
    /// key bytes, used by both sides to compute the human-verifiable
    /// confirmation code (see `continuity_crypto::pairing`).
    PairRequest { device: DeviceInfo },

    /// Sent by the responder once the user has compared and confirmed (or
    /// rejected) the numeric code shown on both screens.
    PairConfirm { accepted: bool },

    /// Clipboard content changed on `origin_device`. `content_hash` lets
    /// receivers dedupe and lets the origin device's own watcher ignore its
    /// own programmatic write instead of re-broadcasting it.
    ClipboardUpdate {
        origin_device: DeviceId,
        content_hash: ContentHash,
        mime: String,
        #[serde(with = "b64")]
        data: Vec<u8>,
    },

    /// Point-to-point file send, step 1: sender offers metadata, receiver's
    /// UI prompts accept/reject (AirDrop-style).
    FileOffer {
        transfer_id: TransferId,
        origin_device: DeviceId,
        file_name: String,
        size_bytes: u64,
        mime: Option<String>,
    },
    FileAccept {
        transfer_id: TransferId,
        accepted: bool,
    },
    FileChunk {
        transfer_id: TransferId,
        seq: u64,
        #[serde(with = "b64")]
        data: Vec<u8>,
    },
    FileComplete {
        transfer_id: TransferId,
        content_hash: ContentHash,
    },

    /// Keepalive / liveness check on the persistent mesh connection.
    Ping,
    Pong,

    /// Remote-control a transport command on the receiving device's
    /// currently-playing media — fire-and-forget, no acknowledgement.
    /// Only macOS acts on this today (see `continuity-daemon::MediaController`);
    /// other platforms silently ignore it.
    MediaCommand { command: MediaCommand },

    /// Pushed by a device whenever its own now-playing state changes
    /// (title/artist/album/artwork/play state) — not a response to
    /// anything, the sender's own `MediaController::now_playing()`
    /// watcher polls for changes and broadcasts them unprompted, mirroring
    /// how `ClipboardUpdate` works.
    NowPlayingUpdate { info: NowPlayingInfo },
}

/// A media transport command sent over `Message::MediaCommand`. Deliberately
/// minimal for now (no volume) — see `continuity-daemon::MediaController`
/// for where a receiving platform acts on these.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MediaCommand {
    PlayPause,
    Next,
    Previous,
}

/// Snapshot of a device's now-playing state, sent over
/// `Message::NowPlayingUpdate`. `artwork` is an empty `Vec` rather than
/// `None` for "no artwork" — the shared `b64` codec below only handles
/// `Vec<u8>` directly, and an empty vec is unambiguous here since real
/// artwork is never zero bytes.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct NowPlayingInfo {
    pub title: Option<String>,
    pub artist: Option<String>,
    pub album: Option<String>,
    #[serde(with = "b64")]
    pub artwork: Vec<u8>,
    pub is_playing: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn message_round_trips_through_json() {
        let msg = Message::ClipboardUpdate {
            origin_device: "abc123".into(),
            content_hash: "deadbeef".into(),
            mime: "text/plain".into(),
            data: b"hello".to_vec(),
        };
        let json = serde_json::to_string(&msg).expect("serialize");
        let back: Message = serde_json::from_str(&json).expect("deserialize");
        match back {
            Message::ClipboardUpdate { mime, .. } => assert_eq!(mime, "text/plain"),
            other => panic!("unexpected variant: {other:?}"),
        }
    }
}
